### ISSUE TITLE
Allow ENV files to be passed to BitOps docker

### ISSUE THREAD

**Issue by arm4b** [bitovi/github-actions-deploy-stackstorm#40]
I'd like to pass the custom ENV variables to BitOps Docker to be available during the deployment stage:

```yaml
    steps:
    - id: deploy-st2
      name: Deploy StackStorm
      # extra ENV vars to be passed to BitOps
      env:
        BITOPS_LOGGING_LEVEL: ERROR
        BITOPS_ANSIBLE_DRYRUN: true
        BITOPS_TERRAFORM_COMMAND: plan
      uses: bitovi/github-actions-deploy-stackstorm@main
      with:
        aws_default_region: us-east-1
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        st2_auth_username: ${{ secrets.ST2_AUTH_USERNAME}}
        st2_auth_password: ${{ secrets.ST2_AUTH_PASSWORD}}
```

This way we can potentially control anything BitOps on top of the predefined default inputs in the GH Action. This may provide any level of control for the user and show the power of BitOps as a framework with its ENV vars configuration.

For example, I could do dynamically `dry-run` or `plan` on a PR, but `apply` on a merge as described in the #27 or any level of customization is it logging or something else.

---
To implement this, we can parse the list of `env` vars and pass only the vars starting with `BITOPS_` to the Docker run via `-e`.
As expected, in the end, priority goes to the user-specified ENVs compared to github-action generated ENVs.
